---
title: "每週一圖作業"
output: html_document
params:
  組員: ["小明","小花"]  
  學號: ["410773818","410773293"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
```

```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```

```{r}
class(StuDF)                #[1]"data.frame":指class(StuDF)
typeof(StuDF)               #[1]"list":指type(StuDF)
```

```{r}
class(StuList)               
typeof(StuList) 

# StuList & StuDF,type中都是list, 但實際上，StuDF因為class是dataframe所以其實可以做更多的事
```
```{r}
length(StuDF) # 從向量角度看  # 其實就是有幾個"，"然後再+1
nrow(StuDF) # 從矩陣角度看
#length(StuDF) 裡面只有五個element，但每一個element都是一個list or vector
```

```{r}
str(StuDF)    #檢查變數結構
head(StuDF)   #檢查前6筆
tail(StuDF)   #檢查後6筆
```

###Slice

```{r}
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n())  #最後一筆

# 下面跑出４個datafram，分別對應StuDF, slice(StuDF,1:3), slice(StuDF,4:5), slice(StuDF,n())
```

#### 使用slice顯示最後2筆資料。
```{r}
slice(StuDF,(n()-1):n())   # method1(good)
slice(StuDF, 7:8)          # method2(you have to count and know how much data in this dataframe)
```

```{r}
StuDF
slice(StuDF,-5:-7)    #第五到七個資料不要
slice(StuDF,-(5:7))   #a better expression, would not mislead to python expression
```

```{r}
5:7
-(5:7)
c(-5, -6, -7)
```

### 只要1,4,7
```{r}
slice(StuDF,c(1,4,8))
slice(StuDF,-c(2:3),-c(5:7))
```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```

### Pop quiz
1. 檢查變數結構
2. 顯示前4筆，後3筆，中間第101到110筆。
```{r}
str(collegeData)               #check data style
slice(collegeData,c(1:4), n()-2:n(), (101:110))
slice(collegeData, c(1:4))
slice(collegeData, n()-2:n())
slice(collegeData, c(101:110))
```

```{r}
StuDF
mutate(StuDF,
       調分後成績=成績+10)  #最右邊多一個新變數，但並沒有回存，所以dataframe不變
transmute(StuDF,
       調分後成績=成績+10)  #不保留其他變數（只有新創的）
```
```{r}
# method1
StuDF
mutate(StuDF,
       調分後成績=成績+10) -> StuDF
# method2
# StuDF
# StuDF <- mutate(StuDF,
#       調分後成績=成績+10) 
```
```{r}
# 不使用dplyr則必需使用$取出變數向量（成績）後，進行運算再回存到data frame裡新的變數（調分後成績）裡：
StuDF$調分後成績 <-
  StuDF$成績+10
# 從list角度看
StuDF
```


### Pop Quiz
在collegeData:
1. 新增變數男生及女生,其值為「一到四年級」所有男生及女生的加總。（男生使用dplyr, 女生不使用dplyr）
2. 新增變數男女生比，其值為前述男生/女生。
```{r}
# 1
collegeData
mutate(collegeData,
       男生=一年級男生+二年級男生+三年級男生+四年級男生)->collegeData

collegeData$女生 <-
  collegeData$一年級女生+collegeData$二年級女生+collegeData$三年級女生+collegeData$四年級女生
# 2
collegeData$男女生比<-collegeData$男生/collegeData$女生
```


```{r}
collegeData
mutate(collegeData,
       男生=一年級男生+二年級男生+三年級男生+四年級男生)-> collegeData
```

